version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - nilerr
    - errorlint
    - exhaustive

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G304
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
