version: 2

builds:
  - main: ./cmd/gcgo
    binary: gcgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mosajjal/gcgo/internal/version.Version={{.Version}}
      - -X github.com/mosajjal/gcgo/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/mosajjal/gcgo/internal/version.BuildTime={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
